print("Salom")
print("Yangi qator")
print("Yana yangi qator")
print("Yana yangi qator")
print("Yana yangi qator")
print("Yana yangi qator")
print("Yana yangi qator")
print("Yana yangi qator")
print("Yana yangi qator")
print("Yana yangi qator")
print("Yana yangi qator")
print("Yana yangi qator")